version: '3'
services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "10011:10011"
    networks:
      - fishOn-network
    depends_on:
      - user-auth-grpc
      - etcd
      - redis
      - mysql
    # Add any other environment variables or configurations specific to service1

  admin-user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "10015:10015"
    networks:
      - fishOn-network
    depends_on:
      - user-auth-grpc
      - etcd
      - redis
      - mysql

  user-auth-grpc:
    build:
      context: ./userAuth-grpc
      dockerfile: Dockerfile
    ports:
      - "10021:10021"
    networks:
      - fishOn-network
    depends_on:
      - etcd
      - redis
      - mysql
    # Add any other environment variables or configurations specific to service2
  mysql:
    image: mysql:5.7
    ports:
      - 13306:3306
      - 3306:3306
      - 23306:33060
    container_name: mysql
    volumes:
      - ./components/mysql/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime
    environment:
      MYSQL_ROOT_PASSWORD: sandman
    restart: always
    networks:
      - fishOn-network

  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: redis
    networks:
      - fishOn-network
    volumes:
      - ./components/redis/data:/data
      #redis config file
      - ./components/redis/config/redis.conf:/usr/local/redis/config/redis.conf
    environment:
      TZ: Asia/Shanghai
    restart: always
    sysctls:
      net.core.somaxconn: 1024
    command: redis-server --requirepass 123456 --appendonly yes


  etcd:
    image: quay.io/coreos/etcd
    ports:
      - 2379:2379
      - 2380:2380
    container_name: etcd
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    environment:
      ETCDCTL_API: 3
    restart: always
    command: /usr/local/bin/etcd --name etcd0 --data-dir /etcd-data --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://0.0.0.0:2379 --listen-peer-urls http://0.0.0.0:2380 --initial-advertise-peer-urls http://0.0.0.0:2380 --initial-cluster etcd0=http://0.0.0.0:2380 --initial-cluster-token tkn --initial-cluster-state new

networks:
   fishOn-network:
    driver: bridge